Proyecto/Controllers/ReunionController.cs
using Proyecto.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Proyecto.Controllers
{
    public class ReunionController : Controller
    {
		// GET: Reunion
		public ActionResult Index()
		{						//es el context
			using (var db = new ReunioneEntities())
			{
				return View(db.Reunion.ToList());
			}

		}

		public ActionResult Agregar()
		{
			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Agregar(Reunion re)
		{
			//verifica nuevamente si algun dato del modelo no es valido
			if (!ModelState.IsValid)
				return View();
			try
			{						
				using (var db = new ReunioneEntities())
				{
					db.Reunion.Add(re);
					db.SaveChanges();
					//return RedirectToAction("Index");
					return View();
				}
			}
			catch (Exception ex)
			{
				ModelState.AddModelError("Error al Agregar Reunion", ex);
				return View();
			}
		}

		//retorna los datos de clientes de la vista cliente
		//con la ayuda de la vista parcial
		public ActionResult ListarUsuario()
		{
			using (var db = new ReunioneEntities())
			{
				return PartialView(db.Usuarios.ToList());
			}
		}
		public static string NombreUsuario(int IdCliente)
		{
			using (var db = new ReunioneEntities())
			{
				return db.Usuarios.Find(IdCliente).Nombre_Usuario;
			}
		}

		public ActionResult Detalles(int id)
		{
			using (var db = new ReunioneEntities())
			{
				Reunion cl = db.Reunion.Find(id);
				return View(cl);
			}
		}

		public ActionResult Editar(int id)
		{
			try
			{
				using (var db = new ReunioneEntities())
				{
					//si es nulo dice que no existe, sino selecciona el primero
					//Cliente cont = db.Cliente.Where(c => c.id == id).FirstOrDefault();
					Reunion re = db.Reunion.Find(id);
					return View(re);
				}
			}
			catch (Exception)
			{

				throw;
			}
		}
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Editar(Reunion c)
		{
			//c datos que vienen del formulario
			try
			{
				if (!ModelState.IsValid)
					return View();
				using (var db = new ReunioneEntities())
				{
					//cl es la reunion que se encontro en la BD
					Reunion cl = db.Reunion.Find(c.Id);
					cl.Titulo_Reunion = c.Titulo_Reunion;
					cl.Fecha_Hora = c.Fecha_Hora;
					cl.Id_Usuario = c.Id_Usuario;
					cl.Virtual = c.Virtual;

					db.SaveChanges();
				}

				return RedirectToAction("Index");
			}
			catch (Exception)
			{

				throw;
			}

		}
		public ActionResult Eliminar(int id)
		{
			using (var db = new ReunioneEntities())
			{
				Reunion co = db.Reunion.Find(id);
				db.Reunion.Remove(co);
				db.SaveChanges();
				return RedirectToAction("Index");
			}


		}
		public ActionResult Buscar(string palabra)
		{
			IEnumerable<Reunion> reunion;

			using (var bd = new ReunioneEntities())
			{
				reunion = bd.Reunion;

				if (!String.IsNullOrEmpty(palabra))
				{
					reunion = reunion.Where(l => l.Titulo_Reunion.Contains(palabra));
				}

				reunion = reunion.ToList();
			}

			return View(reunion);
		}
	}
}

Proyecto/Views/Reunion/Agregar.cshtml
@model Proyecto.Models.Reunion
@{
    ViewBag.Title = "Agregar";
    if (Session["userID"] == null)
    {
        Response.Redirect("~/Login/Index");
    }
    else if (@Session["userRol"].ToString() != "Admin" && Session["userID"] != null)
    {
        Response.Redirect("~/Home/About");
    }
    else
    {
        Layout = "~/Views/Shared/_Layout.cshtml";
    }
}
<h2>Agregar</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Reunion</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Titulo_Reunion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titulo_Reunion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titulo_Reunion, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                @Html.ValidationMessageFor(model => model.Fecha_Hora, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Fecha_Hora, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fecha_Hora, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fecha_Hora, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Id_Usuario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Action("ListarUsuario")
                @Html.ValidationMessageFor(model => model.Id_Usuario, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Virtual, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Virtual)
                    @Html.ValidationMessageFor(model => model.Virtual, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Agregar" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Regresar", "Index")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script type="text/javascript">
    $(function () {
        $('#datetimepicker2').datetimepicker({
            locale: 'ru'
        });
    });
</script>

Proyecto/Views/Reunion/Buscar.cshtml
@model IEnumerable<Proyecto.Models.Reunion>

@{
    ViewBag.Title = "Buscar";
    if (Session["userID"] == null)
    {
        Response.Redirect("~/Login/Index");
    }
    else if (@Session["userRol"].ToString() != "Admin" && Session["userID"] != null)
    {
        Response.Redirect("~/Home/About");
    }
    else
    {
        Layout = "~/Views/Shared/_Layout.cshtml";
    }
}

<h2>Buscar</h2>

<p>
    @Html.ActionLink("Regresar", "Index")
</p>
<table class="table table-bordered">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Titulo_Reunion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fecha_Hora)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Id_Usuario)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Virtual)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Titulo_Reunion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fecha_Hora)
            </td>
            <td>
                @Proyecto.Controllers.ReunionController.NombreUsuario(item.Id_Usuario)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Virtual)
            </td>
            <td>
                @Html.ActionLink("Editar", "Editar", new { id = item.Id }) |
                @Html.ActionLink("Detalles", "Detalles", new { id = item.Id }) |
                @Html.ActionLink("Eliminar", "Eliminar", new { id = item.Id }, new { @class = "cElimina" })
            </td>
        </tr>
    }

</table>
@section scripts{
    <script>
        $(".cElimina").click(function (event) {
            if (!confirm("Esta seguro que desea eliminar ??")) {
                event.preventDefault();
            }
        });
    </script>
}

Proyecto/Views/Reunion/Detalles.cshtml
@model Proyecto.Models.Reunion
@{
    ViewBag.Title = "Detalles";
    if (Session["userID"] == null)
    {
        Response.Redirect("~/Login/Index");
    }else if (@Session["userRol"].ToString() != "Admin" && Session["userID"] != null )
    {
        Response.Redirect("~/Home/About");
    }else{
        Layout = "~/Views/Shared/_Layout.cshtml";
    }
}

<h2>Detalles</h2>
<div>
    <h4>Reunion</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Titulo_Reunion)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Titulo_Reunion)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Fecha_Hora)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Fecha_Hora)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Id_Usuario)
        </dt>
        <dd>
            @Proyecto.Controllers.ReunionController.NombreUsuario(Model.Id_Usuario)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Virtual)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Virtual)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Regresar", "Index")
</p>

Proyecto/Views/Reunion/Editar.cshtml
@model Proyecto.Models.Reunion

@{
    ViewBag.Title = "Editar";
    if (Session["userID"] == null)
    {
        Response.Redirect("~/Login/Index");
    }else if (@Session["userRol"].ToString() != "Admin" && Session["userID"] != null )
    {
        Response.Redirect("~/Home/About");
    }else{
        Layout = "~/Views/Shared/_Layout.cshtml";
    }
}

<h2>Editar</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Reunion</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Titulo_Reunion, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Titulo_Reunion, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Titulo_Reunion, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Fecha_Hora, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Fecha_Hora, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Fecha_Hora, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Id_Usuario, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.Action("ListarUsuario")
            @Html.ValidationMessageFor(model => model.Id_Usuario, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Virtual, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Virtual)
                @Html.ValidationMessageFor(model => model.Virtual, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Modificar" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Regresar", "Index")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script type="text/javascript">
    $(function () {
        $('#datetimepicker2').datetimepicker({
            locale: 'ru'
        });
    });
</script>

Proyecto/Views/Reunion/Index.cshtml
@model IEnumerable<Proyecto.Models.Reunion>



    @{
        ViewBag.Title = "Reuniones";
        if (Session["userID"] == null)
        {
            Response.Redirect("~/Login/Index");
        }
        else if (@Session["userRol"].ToString() != "Admin" && Session["userID"] != null)
        {
            Response.Redirect("~/Home/About");
        }
        else
        {
            Layout = "~/Views/Shared/_Layout.cshtml";
        }
    }


<h2>Reuniones</h2>

<p>
    @Html.ActionLink("Agregar Nueva Reunión", "Agregar")
</p>

@using (Html.BeginForm("Buscar", "Reunion", FormMethod.Get))
{
    <p white>
        Término a buscar: @Html.TextBox("palabra")
        <input type="submit" value="Buscar" class="btn btn-default" />
    </p>
}


<table class="table table-bordered">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Titulo_Reunion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fecha_Hora)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Id_Usuario)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Virtual)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Titulo_Reunion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fecha_Hora)
            </td>
            <td>
                @Proyecto.Controllers.ReunionController.NombreUsuario(item.Id_Usuario)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Virtual)
            </td>
            <td>
                @Html.ActionLink("Editar", "Editar", new { id = item.Id }) |
                @Html.ActionLink("Detalles", "Detalles", new { id = item.Id }) |
                @Html.ActionLink("Eliminar", "Eliminar", new { id = item.Id }, new { @class = "cElimina" })
            </td>
        </tr>
    }
</table>
@section scripts{
    <script>
        $(".cElimina").click(function (event) {
            if (!confirm("Esta seguro que desea eliminar ??")) {
                event.preventDefault();
            }
        });
    </script>
}

Proyecto/Views/Reunion/ListarUsuario.cshtml
@model IEnumerable<Proyecto.Models.Usuarios>
<select class="form-control" id="Id_Usuario" name="Id_Usuario">
	//razor implementa tanto codigo html como codigo del servidor
	//con arroba utilizamos codigo servidor
	@foreach (var item in Model)
	{
		<option value="@item.Id">@item.Nombre_Usuario</option>
	}
</select>
	